const AppointmentCreated = (appointment) => {
  return `<!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Roboto" 
rel="stylesheet" type="text/css"><!--<![endif]--><style>
*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.image_block img+div{display:none} @media (max-width:520px){.row-content{width:100%!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
</style></head><body style="background-color:transparent;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:transparent"><tbody><tr><td><table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td>
<table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#343446;width:500px" width="500"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" 
width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:30px;padding-left:20px;padding-right:20px;padding-top:10px"><div style="font-family:sans-serif"><div class style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#4b4b60;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p 
style="margin:0;font-size:12px;text-align:center;mso-line-height-alt:14.399999999999999px"><strong><span style="font-size:30px;">Appointment Booked!</span></strong></p></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:Tahoma,Verdana,sans-serif"><div class 
style="font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;font-size:12px;mso-line-height-alt:14.399999999999999px;color:#4b4b60;line-height:1.2"><p style="margin:0;font-size:12px;text-align:left;mso-line-height-alt:14.399999999999999px">
<span style="font-size:14px;">Appointment details attached below:<br />Name: ${appointment.appointmentName}<br />Email: ${appointment.appointmentEmail}<br />Phone: ${appointment.phoneNumber}<br />Address: ${appointment.address}<br />Date: ${appointment.date}<br />Start time: ${appointment.startTime}<br />Duration: ${appointment.duration.label}<br />Notes:${appointment.description} <a href="https://app.prorouting.ai/appointment/${appointment.id}" target="_blank" class="" style="text-decoration: underline; color: #343446;" rel="noopener"></a></span></p></div></div></td></tr></table><table class="button_block block-3" 
width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="left">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="https://app.prorouting.ai/appointment/${appointment.id}" style="height:34px;width:217px;v-text-anchor:middle;" arcsize="30%" stroke="false" fill="false"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#343446; font-family:Tahoma, Verdana, sans-serif; font-size:12px"><![endif]-->
<a href="https://app.prorouting.ai/appointment/${appointment.id}" target="_blank" style="text-decoration:none;display:inline-block;color:#343446;background-color:transparent;border-radius:10px;width:auto;border-top:0px solid transparent;font-weight:400;border-right:0px solid transparent;border-bottom:0px solid transparent;border-left:0px solid transparent;padding-top:5px;padding-bottom:5px;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;font-size:12px;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:20px;padding-right:20px;font-size:12px;display:inline-block;letter-spacing:normal;"><span dir="ltr" style="word-break: break-word; line-height: 24px;"><u>Cancel / Reschedule Appointment</u></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#343446;width:500px" 
width="500"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="20" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#a1a2b2;line-height:1.2;font-family:Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:12px;text-align:center;mso-line-height-alt:14.399999999999999px"><span style="font-size:14px;">The email was sent to ${appointment.email}. To no longer receive these emails, <a href="{% unsubscribe_url %}" target="_blank" style="text-decoration: underline; color: #343446;" rel="noopener">unsubscribe</a> here.</span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table></td></tr>
</tbody></table><!-- End --></body></html>`;
};

module.exports = {
  AppointmentCreated,
};
